### ISSUE TITLE
terms lacking correct namespace in OBO file

### ISSUE THREAD

**Issue by sbello** [DiseaseOntology/HumanDiseaseOntology#569]
The term shellfish allergy (DOID:0060495) and all of it's children do not have the correct namespace in the newly released doid-merged.obo and doid.obo files. Please fix this as it breaks our load.
Thanks,
Sue

**Comment by lschriml** [comment]
Thank you Sue,
   I see what you mean, 
I have fixed these. 
They came in via a robot load of IEDB terms.
We will add this check to our QC.

I am pushing out new files now.

Cheers,
Lynn

**Comment by sbello** [comment]
Thanks Lynn!

**Comment by sbello** [comment]
Hi Lynn,
I checked the current versions of the files, including the doid-edit file and these terms are still missing the correct namespace. Possibly something went wrong with your commit on Friday. Would you please double check.
Thanks
Sue

**Comment by lschriml** [comment]
Hello Sue,
 I will review these this morning.

Cheer,
Lynn

**Comment by rctauber** [comment]
I haven’t gotten a chance to add the namespaces in yet, but I’ll take care
of it this afternoon.

**Comment by lschriml** [comment]
No worries,
 I am adding them in now.

But it would be great to add this in as part of our overall QC checks for the DO.

Cheers,
Lynn

**Comment by lschriml** [comment]
Hello Sue,
   Weird, I have re-added the disease_ontology name space.

Becky did a global search of DO and we have made updates where needed
To ensure all DOIDs have the has obo namespace correctly populated.

A new release has been pushed out.

Cheers,
Lynn

**Comment by sbello** [comment]
Sorry to be a pest but now the OBO files are throwing the error below when I try to open them in obo.edit.
 
Load error with path file:C:/Users/smb/Documents/HumanDiseaseOntology/src/ontology/doid-merged.obo String index out of range: -1 
java.lang.String.substring(Unknown Source)
org.obo.dataadapter.OBOParseEngine.parseTagValue(OBOParseEngine.java:570)
org.obo.dataadapter.OBOParseEngine.parseTag(OBOParseEngine.java:1018)
org.obo.dataadapter.OBOParseEngine.doParse(OBOParseEngine.java:404)
org.obo.dataadapter.AbstractParseEngine.parse(AbstractParseEngine.java:43)
org.obo.dataadapter.AbstractParseEngine.parse(AbstractParseEngine.java:68)
org.obo.dataadapter.OBOFileAdapter.doOperation(OBOFileAdapter.java:270)
org.bbop.dataadapter.DataAdapterOperationTask.execute(DataAdapterOperationTask.java:43)
org.bbop.util.AbstractTaskDelegate.run(AbstractTaskDelegate.java:60)
org.bbop.swing.BackgroundEventQueue$BackgroundEventThread.executeTask(BackgroundEventQueue.java:137)
org.bbop.swing.BackgroundEventQueue$BackgroundEventThread.run(BackgroundEventQueue.java:79)

**Comment by lschriml** [comment]
Fixed, files pushed.

**Comment by sbello** [comment]
Looks good. I've asked Sharon to run a test load on our system to make sure but I think we are good to go. Thanks for fixing this so quickly.

**Comment by lschriml** [comment]
No problem, happy to do it. 
Cheers,
Lynn
